#!/usr/bin/env node

var program = require('commander');

program
  .version('0.0.1', '-v, --version')
  .command('generate')
  .alias('gen')
  .description('generates randomized patches')
  .option('-a, --author <author>', 'author of the patches')
  .option('-n, --num-patches <n>', 'number of patches to create (1 - 1000), default = 64')
  .option('-p, --path <path>', 'path to Helm presets directory (must already exist)')
  .option('-b, --bank-name <bank-name>', 'directory name for the patch bank; default = helmTools')
  .option('-B, --bank-folder <bank-folder>', 'name for the folder within the patch bank; default = generate')
  .option('-P, --patch-base <patch-base>', 'base name for patches; patch numbers will be appended to this')
  .option('-f, --perturb-factor <f>', 'perturbation factor, 0 to 1; default: 0.1')
  .action(function(options){
    let cmd = require ('./commands/generate');
    cmd (options);
  })

  program.command('hybridize [files...]')
  .alias('hyb')
  .description('builds hybrid patches using randomly selected parameters from the specified patches')
  .option('-a, --author <author>', 'author of the patches')
  .option('-n, --num-patches <n>', 'number of patches to create (1 - 1000), default = 64')
  .option('-p, --path <path>', 'path to Helm presets directory (must already exist)')
  .option('-b, --bank-name <bank-name>', 'directory name for the patch bank; default = helmTools')
  .option('-B, --bank-folder <bank-folder>', 'name for the folder within the patch bank; default = hybridize')
  .option('-P, --patch-base <patch-base>', 'base name for patches; patch numbers will be appended to this')
  .option('-f, --perturb-factor <f>', 'perturbation factor, 0 to 1; default: 0')
  .action(function(files, options){
    let cmd = require ('./commands/hybridize');
    cmd (files, options);
  });

  program.command('overlay [files...]')
  .alias('ovr')
  .description('bulk modifies patch settings by overlaying settings from the provided JSON file onto the patches')
  .option('-p, --path <path>', 'path to Helm presets directory (must already exist)')
  .option('-b, --bank-name <bank-name>', 'directory name for the patch bank; default = helmTools')
  .option('-B, --bank-folder <bank-folder>', 'name for the folder within the patch bank; default = hybridize')
  .option('-o, --overlay-json <overlay-json>', 'JSON file of settings; should mirror the patch format; only settings and modulations will be overlaid')
  .action(function(files, options){
    let cmd = require ('./commands/overlay');
    cmd (files, options);
  });

program.parse(process.argv);
